global using System.Globalization;
global using System.Text;
global using System.Web;
global using CommandLine;
global using CalculateCodeMetrics.CodeAnalysis;
global using CalculateCodeMetrics.GitHubAction;
global using CalculateCodeMetrics.GitHubAction.Analyzers;
global using CalculateCodeMetrics.GitHubAction.Extensions;
global using Markdown;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CodeMetrics;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.FileSystemGlobbing;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using static CommandLine.Parser;
