name: '.NET code metrics'

on:
  pull_request:
    paths:
    - '!CODE_METRICS.md'
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 1

    - name: .NET code metrics
      id: dotnet-code-metrics
      uses: WouterDeKort/CodeQualityDemo/github-actions/CalculateCodeMetrics@main
      with:
        owner: ${{ github.repository_owner }}
        name: ${{ github.repository }}
        branch: ${{ github.ref }}
        dir: ${{ './' }}

    - name: Commit and push changes
      if: ${{ steps.dotnet-code-metrics.outputs.updated-metrics }} == 'true'
      run: |
          git config user.email "codemetricbot@stackoverflow.com"
          git config user.name "#code-metrics"
          git diff --quiet && git diff --staged --quiet || git commit -am 'Automated cod metrics report' && git push
